name: Build Dolphin-Emu AppImage

on:
  schedule:
    - cron: '0 0 * * 1'  # Sync every Monday at midnight UTC
  workflow_dispatch:  # Allows manual trigger via GitHub Actions UI

jobs:
  build-in-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/my-image:latest
      options: --privileged --device=/dev/fuse
      
    steps:
      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token
        env:
          GH_CONFIG_DIR: /tmp/
          GH_TOKEN: ${{ github.token }}

      - name: Resync repository
        run: |
          gh repo sync ${{ github.repository_owner }}/dolphin --source dolphin-emu/dolphin --force

      - name: Clone repository
        run: |
          git clone --recurse-submodules https://github.com/${{ github.repository_owner }}/dolphin /tmp/repo
          
      - name: Build App
        run: |
          mkdir -p /tmp/repo/build
          cd /tmp/repo/build
          cmake .. -DLINUX_LOCAL_DEV=true -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          make install DESTDIR=AppDir
          
      - name: Prepare AppImage
        run: |   
          mv /tmp/repo/build/AppDir/usr/share/dolphin-emu/sys /tmp/repo/build/AppDir/usr/bin/Sys
          cat > /tmp/repo/build/AppDir/usr/share/applications/dolphin-emu.desktop <<\EOF
          [Desktop Entry]
          Version=1.0
          Icon=dolphin-emu
          Exec=dolphin-emu
          Terminal=false
          Type=Application
          Categories=Game;Emulator;
          Name=Dolphin Emulator
          GenericName=Wii/GameCube Emulator
          Comment=A Wii/GameCube Emulator
          EOF
          
      - name: Build AppImage
        run: |
          cd /tmp/repo/build
          VERSION=$(git -C . rev-parse --short=7 HEAD)
          linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --plugin checkrt
          appimagetool-x86_64.AppImage AppDir

      - name: Create a new release in another repository
        run: |
          VERSION=$(git -C /tmp/repo/ rev-parse --short=7 HEAD)
          gh release create dolphin-$VERSION-x86_64 --generate-notes -R ${{ github.repository_owner }}/dolphin dolphin-x86_64.AppImage
