name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main  # Trigger on changes pushed to the main branch
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub username (authenticated user)
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token, automatically provided by GitHub Actions

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }} .

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }}
          # Optionally, you can tag the image with a version (e.g., a tag or `latest`)
          docker tag ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/my-image:latest
          docker push ghcr.io/${{ github.repository_owner }}/my-image:latest
